# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4a95b4e5-a240-4754-9101-3e966627449d";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/4a95b4e5-a240-4754-9101-3e966627449d";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/4a95b4e5-a240-4754-9101-3e966627449d";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4a95b4e5-a240-4754-9101-3e966627449d";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/96AD-CC08";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9c65c0ec-9194-4552-aabc-6fcd84d41a5b"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
