# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/b866a56d-17c7-4550-936a-8b0d834fe444";
      fsType = "ext4";
    };

  fileSystems."/media/hdd" = {
    device = "/dev/disk/by-uuid/6f12f68c-bd0e-456a-926a-59d1ffd5cbe6";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress-force=zstd:5"
      "space_cache"
      "autodefrag"
    ];
  };

  fileSystems."/media/ssd" = {
    device = "/dev/disk/by-uuid/add4b883-33d6-4982-9938-41622577f382";
    fsType = "btrfs";
    options = [
      "ssd"
      "noatime"
      "compress-force=zstd:5"
      "space_cache"
      "autodefrag"
    ];
  };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/A385-5AEF";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking.useDHCP = lib.mkDefault false;
  networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
